version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: throttlex-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: throttlex
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
